import img_1 from './assets/img_1.jpg';
import img_2 from './assets/img_2.jpg';
import img_3 from './assets/img_3.jpg';
import img_4 from './assets/img_4.jpg';
import img_5 from './assets/img_5.jpg';

export const aboutUs = [
  {
    id: '1',
    img: img_1,
    title: 'Очаків під щоденними обстрілами:',
    description: ' Як миколаївські волонтери допомагають місцевим, домівки яких постраждали',
    link: 'https://svidok.info/ru/news/64533',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '2',
    img: img_2,
    title: 'Rebel.volunteers:',
    description: 'Як у Миколаєві діє громадське об’єднання волонтерів',
    link: 'https://svidok.info/ru/news/64533',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '3',
    img: img_3,
    title: 'Rebel volunteers: заради спільної перемоги',
    link: 'https://uacrisis.org/uk/rebel-volunteers',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '4',
    img: img_4,
    title: 'Герої тилу:',
    description: 'У Миколаєві волонтери не лише допомагають фронту, а й шиють брендований мілітарі одяг',
    link: 'https://uacrisis.org/uk/rebel-volunteers',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '5',
    img: img_5,
    title: 'Миколаїв — синонім мужності',
    description: 'Волонтерка розповіла про свою діяльність та рідне місто',
    link: 'https://www.youtube.com/watch?v=BsJsWIXCKLM',
    textButton: 'Дивитись сюжет повністю',
  },
  {
    id: '11',
    img: img_1,
    title: 'Очаків під щоденними обстрілами:',
    description: ' Як миколаївські волонтери допомагають місцевим, домівки яких постраждали',
    link: 'https://svidok.info/ru/news/64533',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '12',
    img: img_2,
    title: 'Rebel.volunteers:',
    description: 'Як у Миколаєві діє громадське об’єднання волонтерів',
    link: 'https://svidok.info/ru/news/64533',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '13',
    img: img_3,
    title: 'Rebel volunteers: заради спільної перемоги',
    link: 'https://uacrisis.org/uk/rebel-volunteers',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '14',
    img: img_4,
    title: 'Герої тилу:',
    description: 'У Миколаєві волонтери не лише допомагають фронту, а й шиють брендований мілітарі одяг',
    link: 'https://uacrisis.org/uk/rebel-volunteers',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '15',
    img: img_5,
    title: 'Миколаїв — синонім мужності',
    description: 'Волонтерка розповіла про свою діяльність та рідне місто',
    link: 'https://www.youtube.com/watch?v=BsJsWIXCKLM',
    textButton: 'Дивитись сюжет повністю',
  },
  {
    id: '6',
    img: img_1,
    title: 'Очаків під щоденними обстрілами:',
    description: ' Як миколаївські волонтери допомагають місцевим, домівки яких постраждали',
    link: 'https://svidok.info/ru/news/64533',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '7',
    img: img_2,
    title: 'Rebel.volunteers:',
    description: 'Як у Миколаєві діє громадське об’єднання волонтерів',
    link: 'https://svidok.info/ru/news/64533',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '8',
    img: img_3,
    title: 'Rebel volunteers: заради спільної перемоги',
    link: 'https://uacrisis.org/uk/rebel-volunteers',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '9',
    img: img_4,
    title: 'Герої тилу:',
    description: 'У Миколаєві волонтери не лише допомагають фронту, а й шиють брендований мілітарі одяг',
    link: 'https://uacrisis.org/uk/rebel-volunteers',
    textButton: 'Читати статтю повністю',
  },
  {
    id: '10',
    img: img_5,
    title: 'Миколаїв — синонім мужності',
    description: 'Волонтерка розповіла про свою діяльність та рідне місто',
    link: 'https://www.youtube.com/watch?v=BsJsWIXCKLM',
    textButton: 'Дивитись сюжет повністю',
  },
];
