export const list = [
  {
    id: '1',
    title_uk: 'Тактика',
    title_en: 'Tactics',
    items: [
      { id: '1', quantity: 0, title_en: 'Evacuation stretchers', title_uk: 'Ноші евакуаційні' },
      { id: '2', quantity: 0, title_en: 'Active headphones', title_uk: 'Навушники активні' },
      { id: '3', quantity: 0, title_en: 'Israeli bandage 4`', title_uk: 'Ізраїльський бандаж 4' },
      { id: '4', quantity: 0, title_en: 'Occlusive dressings', title_uk: 'Оклюзійні наліпки' },
      { id: '5', quantity: 0, title_en: 'Tactical scissors', title_uk: 'Тактичні ножиці' },
      { id: '6', quantity: 0, title_en: 'Foil blankets', title_uk: 'Термоковдри фольговані' },
      {
        id: '7',
        quantity: 0,
        title_en: 'BurnTec or similar hydrogel burn dressing',
        title_uk: 'Протиопікова гідрогелева пов’язка (наприклад - BurnTec)',
      },
      { id: '8', quantity: 0, title_en: 'Ballistic goggles', title_uk: 'Балістичні окуляри' },
      { id: '9', quantity: 0, title_en: 'Tactical gloves (fingered)', title_uk: 'Тактичні рукавички (з пальцями)' },
      { id: '10', quantity: 0, title_en: 'Knee and elbow pads', title_uk: 'Наколінники, налокітники' },
      { id: '11', quantity: 0, title_en: 'Personal Protective Equipment (PPE)', title_uk: 'РПС' },
    ],
  },
  {
    id: '2',
    title_uk: 'Медицина',
    title_en: 'Medicine',
    items: [
      {
        id: '1',
        quantity: 0,
        title_en: 'Antiviral/symptomatic teas/tablets',
        title_uk: 'Протизастудні/симптоматичні чаї/таблетки',
      },
      { id: '2', quantity: 0, title_en: 'Heating rubs', title_uk: 'Зігріваючі розтирання' },
      { id: '3', quantity: 0, title_en: 'Nasal/ear/eye drops', title_uk: 'Краплі в ніс/вухо/очі' },
      { id: '4', quantity: 0, title_en: 'Throat sprays/tablets', title_uk: 'Спреї/таблетки для горла' },
      { id: '5', quantity: 0, title_en: 'Cough/throat lozenges', title_uk: 'Таблетки/льодяники від кашлю/для горла' },
      {
        id: '6',
        quantity: 0,
        title_en: 'Vitamin C/comprehensive vitamins',
        title_uk: 'Вітамін С/комплексні вітаміни',
      },
      { id: '7', quantity: 0, title_en: 'Nootropic tablets/ampoules', title_uk: 'Ноотропи таб/амп' },
      { id: '8', quantity: 0, title_en: 'Dibazol injections', title_uk: 'Дібазол ін`єкції' },
      { id: '9', quantity: 0, title_en: 'Prozerin injections', title_uk: 'Прозерин ін`єкції' },
      { id: '10', quantity: 0, title_en: 'Papaverine injections', title_uk: 'Папаверин ін`єкції' },
      { id: '11', quantity: 0, title_en: 'Platyphyllin injections', title_uk: 'Платифілін ін`єкції' },
      {
        id: '12',
        quantity: 0,
        title_en: 'Diclofenac injections/tablets/ointments',
        title_uk: 'Диклофенак ін`єкції /таб/мазі',
      },
      {
        id: '13',
        quantity: 0,
        title_en: 'Dexketoprofen injections/tablets/powders',
        title_uk: 'Декскетопрофен ін`єкції /таб/порошки',
      },
    ],
  },
  {
    id: '3',
    title_uk: 'Їжа',
    title_en: 'Food',
    items: [
      { id: '1', quantity: 0, title_en: 'Canned meats', title_uk: 'Консерви м’ясні' },
      { id: '2', quantity: 0, title_en: 'Pâtés', title_uk: 'Паштети' },
      { id: '3', quantity: 0, title_en: 'Canned fish', title_uk: 'Консерви рибні' },
      { id: '4', quantity: 0, title_en: 'Canned vegetables', title_uk: 'Консерви овочеві' },
      { id: '5', quantity: 0, title_en: 'Canned fruits', title_uk: 'Консерви фруктові' },
      { id: '6', quantity: 0, title_en: 'Dried sausage', title_uk: 'Ковбаса вялена' },
      { id: '7', quantity: 0, title_en: 'Condensed milk', title_uk: 'Згущене молоко' },
      { id: '8', quantity: 0, title_en: 'Coffee', title_uk: 'Кава' },
      { id: '9', quantity: 0, title_en: 'Tea', title_uk: 'Чай' },
      { id: '10', quantity: 0, title_en: 'Oil', title_uk: 'Олія' },
      { id: '11', quantity: 0, title_en: 'Dehydrated food', title_uk: 'Сублімована їжа' },
      { id: '12', quantity: 0, title_en: 'MREs (Meal, Ready-to-Eat)', title_uk: 'Сухпайки' },
    ],
  },
];
