export const list = [
  {
    id: '1',
    title_uk: 'Тактика',
    title_en: 'Tactics',
    items: [
      {
        id: '1',

        links: [
          'https://www.narescue.com/combat-application-tourniquet-c-a-t.html',
          'https://shop.tqdnipro.com/dzhhut-krovospynnyi-dnipro-gen-2/',
          'https://www.instagram.com/tacmedinua?igshid=Mzc1MmZhNjY%3D',
        ],
        quantity: 0,
        title_en: 'Tourniquets (Cat 7/SOFTT-W/SICH)',
        title_uk: 'Турнікети (Cat 7/SOFTT-W/SICH)',
      },
      {
        id: '2',

        links: ['https://www.uii.in.ua/product/materialy/polyamide/noshi-evakuaczijni-odnoslojni'],
        quantity: 0,
        title_en: 'Evacuation stretchers',
        title_uk: 'Ноші евакуаційні',
      },
      {
        id: '3',
        quantity: 0,
        title_en: 'Active headphones',
        title_uk: 'Навушники активні',
        links: ['https://prom.ua/ua/Pritsely-i-mushki'],
      },
      {
        id: '4',
        quantity: 0,
        title_en: 'Israeli bandage 4`',
        title_uk: 'Ізраїльський бандаж 4',
        links: ['https://hunter.rozetka.com.ua/ua/353704527/p353704527/'],
      },
      {
        id: '5',
        quantity: 0,
        title_en: 'Occlusive patches',
        title_uk: 'Оклюзійні наліпки',
        links: ['https://kyivguma.com.ua/ua/p1634639471-povyazka-oklyuzijna-torakalna.html'],
      },
      {
        id: '6',
        quantity: 0,
        title_en: 'Tactical scissors',
        title_uk: 'Тактичні ножиці',
        links: [
          'https://www.timeforrescue.com.ua/product/%D0%BD%D0%BE%D0%B6%D0%B8%D1%86%D1%96-%D0%B0%D1%82%D1%80%D0%B0%D0%B2%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D1%96-%D1%82%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D1%96/',
        ],
      },
      { id: '7', quantity: 0, title_en: 'Foil blankets', title_uk: 'Термоковдри фольговані' },
      {
        id: '8',
        quantity: 0,
        title_en: 'Antishock hydrogel dressing (e.g., BurnTec)',
        title_uk: 'Протиопікова гідрогелева пов’язка (наприклад - BurnTec)',
        links: ['https://www.timeforrescue.com.ua/product/%D0%BE%D0%BF%D1%96%D0%BA%D1%83%D0%BD-10%D1%8510-1/'],
      },
      {
        id: '9',
        quantity: 0,
        title_en: 'Ballistic goggles',
        title_uk: 'Балістичні окуляри',
        links: ['https://shimano.kiev.ua/ochki-shimano-nexus-orange-clone.html'],
      },
      {
        id: '10',
        quantity: 0,
        title_en: 'Tactical gloves (with fingers)',
        title_uk: 'Тактичні рукавички (з пальцями)',
        links: ['https://killa.com.ua/m-tac-perchatki-assault-mk6-oliva.html'],
      },
      {
        id: '11',
        quantity: 0,
        title_en: 'Knee and elbow pads',
        title_uk: 'Наколінники, налокітники',
        links: ['https://hugo.com.ua/ua/p1663573605-komplekt-zaschity-nalokotniki.html'],
      },
      {
        id: '12',
        quantity: 0,
        title_en: 'Load-bearing shoulder system',
        title_uk: 'РПС',
        links: ['https://tyrwear.com.ua/ua/p1658362374-remenno-plechevaya-sistema.html'],
      },
      {
        id: '13',
        quantity: 0,
        title_en: 'Plate carrier class 4 (certified/tested)',
        title_uk: 'Плитоноски, плити від 4 класу (сертифіковані/відстріляні) посилання',
        links: [
          'https://tyrwear.com.ua/ua/p1658243149-plitonoska-neptun-multikam.html',
          'https://ukrainianarmor.com/shop/bronya/broneplyty/',
        ],
      },
      {
        id: '14',
        quantity: 0,
        title_en: 'Magazine pouch inserts (for 30/45 rounds)',
        title_uk: 'Підсумки під магазини (на 30/45 набоїв)',
        links: ['https://tyrwear.com.ua/ua/p1688441411-podsumok-dlya-magazina.html'],
      },
      {
        id: '15',
        quantity: 0,
        title_en: 'Tactical belts',
        title_uk: 'Тактичні ремені',
      },
      {
        id: '16',
        quantity: 0,
        title_en: 'Тactical flashlights (with red light)',
        title_uk: 'Татктичні ліхтарики(з червоним світлом)',
        links: ['https://rozetka.com.ua/ua/skif-outdoor-3890166/p340571014/'],
      },
      {
        id: '17',
        quantity: 0,
        title_en: 'Tactical knives',
        title_uk: 'Тактичні ножі',
        links: [
          'https://epicentrk.ua/ua/shop/mplc-nizh-turistichnii-gerber-scout-bear-grylls-dlya-vizhivannya-1ecc7941-f9cd-6a9c-878e-5beeea9d41a3.html',
        ],
      },
      {
        id: '18',
        quantity: 0,
        title_en: 'Tactical backpacks',
        title_uk: 'Тактичні рюкзаки',
        links: ['https://killa.com.ua/m-tac-shturmovoy-ryukzak-assault-pack-large-olive.html'],
      },
      {
        id: '19',
        quantity: 0,
        title_en: 'Radios (walkie-talkies)',
        title_uk: 'Рації',
        links: ['https://prom.ua/ua/Peregovornye-ustrojstva'],
      },
      {
        id: '20',
        quantity: 0,
        title_en: 'Binoculars',
        title_uk: 'Біноклі',
        links: ['https://bresserua.com/ru/bresser-binosail-7x50-wp-compass-reticle-9666932/'],
      },
      {
        id: '21',
        quantity: 0,
        title_en: 'Rangefinders',
        title_uk: 'Далекоміри',
        links: ['https://profoptica.com.ua/ua/lazernyy-dalnomer-vortex-viper-hd-3000-lrf-vp3000/'],
      },
      {
        id: '22',
        quantity: 0,
        title_en: 'Mavic 3 drones',
        title_uk: 'Дрони Мавік 3',
        links: ['https://stylus.ua/uk/dji-mavic-3-fly-more-combo-cpma0000045202-p867076c1511.html'],
      },
      {
        id: '23',
        quantity: 0,
        title_en: 'Drone batteries',
        title_uk: 'Акумулятори для дронів',
      },
      {
        id: '24',
        quantity: 0,
        title_en: 'EcoFlow stations',
        title_uk: 'Ecoflow станції',
        links: [
          'https://ecodrive.in.ua/portativnaya-zaryadnaya-stanciya-mini-elektrostanciya-dlya-doma-ecoflow-river-600-vt-256-vtch/',
        ],
      },
      {
        id: '25',
        quantity: 0,
        title_en: 'Gas burners or camping stoves',
        title_uk: 'Газові пальники або примуси/буржуйки',
        links: ['https://killa.com.ua/uk/gorelka-gazovaya-360-degrees-furno-stove-sts-360furnostove.html'],
      },
      {
        id: '26',
        quantity: 0,
        title_en: 'Camping cookware',
        title_uk: 'Туристичний посуд',
      },
      {
        id: '27',
        quantity: 0,
        title_en: 'Disposable shower',
        title_uk: 'Одноразовий душ',
      },
      {
        id: '28',
        quantity: 0,
        title_en: 'Fleece jackets',
        title_uk: 'Флісові кофти',
      },
      {
        id: '29',
        quantity: 0,
        title_en: 'Underwear (briefs)',
        title_uk: 'Білизна(труси)',
      },
      {
        id: '30',
        quantity: 0,
        title_en: 'Sleeping bags',
        title_uk: 'Спальники',
      },
      {
        id: '31',
        quantity: 0,
        title_en: 'Sleeping pads',
        title_uk: 'Каремати',
      },
      {
        id: '32',
        quantity: 0,
        title_en: 'Rain ponchos + Gaiters (for rain)',
        title_uk: 'Дощовики+Гамаші (від дощу)',
        links: ['https://prom.ua/ua/p1800505548-dozhdevik-poncho-kamuflyazhnyj.html'],
      },
      {
        id: '33',
        quantity: 0,
        title_en: 'Thermoses 1/1.5 liters',
        title_uk: 'Термоси 1/1.5 л.',
        links: [
          'https://norfinukraine.com/thermos/tproduct/338245343-281673187911-termos-tramp-basic-hak-1-l-utrc-113-khak',
        ],
      },
      {
        id: '34',
        quantity: 0,
        title_en: 'Earless helmets',
        title_uk: 'Шоломи безвухі',
        links: ['https://ukrainianarmor.com/shop/sholomy/'],
      },
      {
        id: '35',
        quantity: 0,
        title_en: 'AK-74 silencer',
        title_uk: 'Глушник на АК-74',
        links: ['https://prom.ua/ua/c3732187-bronya-nikolaev.html'],
      },
      {
        id: '36',
        quantity: 0,
        title_en: 'Power banks from 10,000',
        title_uk: 'Павербанки від 10000',
      },
    ],
  },
  {
    id: '2',
    title_uk: 'Медицина',
    title_en: 'Medicine',
    items: [
      {
        id: '1',
        quantity: 0,
        title_en: 'Anti-cold/symptomatic teas/tablets',
        title_uk: 'Протизастудні/симптоматичні чаї/таблетки',
      },
      { id: '2', quantity: 0, title_en: 'Warming ointments', title_uk: 'Зігріваючі розтирання' },
      { id: '3', quantity: 0, title_en: 'Nose/ear/eye drops', title_uk: 'Краплі в ніс/вухо/очі' },
      { id: '4', quantity: 0, title_en: 'Throat sprays/tablets', title_uk: 'Спреї/таблетки для горла' },
      {
        id: '5',
        quantity: 0,
        title_en: 'Cough/throat lozenges/tablets',
        title_uk: 'Таблетки/льодяники від кашлю/для горла',
      },
      {
        id: '6',
        quantity: 0,
        title_en: 'Vitamin C/complex vitamins',
        title_uk: 'Вітамін С/комплексні вітаміни',
      },
      { id: '7', quantity: 0, title_en: 'Nootropic tablets/ampoules', title_uk: 'Ноотропи таб/амп' },
      {
        id: '8',
        quantity: 0,
        title_en: 'Diclofenac injections/tablets/ointments',
        title_uk: 'Диклофенак ін`єкції/таб/мазі',
      },
      {
        id: '9',
        quantity: 0,
        title_en: 'Dexketoprofen injections/tablets/powders',
        title_uk: 'Декскетопрофен ін`єкції /таб/порошки',
      },
      {
        id: '10',
        quantity: 0,
        title_en: 'Renalgan/No-shpa tablets/ampoules',
        title_uk: 'Реналган/Но-шпа таблетки/амп',
      },
      { id: '11', quantity: 0, title_en: 'Ketorolac ampoules/tablets', title_uk: 'Кеторолак амп/таб' },
      { id: '12', quantity: 0, title_en: 'Nimesulide tablets/ointments', title_uk: 'Німесулід таб/мазі' },
      { id: '13', quantity: 0, title_en: 'Enzymes', title_uk: 'Ферменти ' },
      { id: '14', quantity: 0, title_en: 'Pantoprazole/Omeprazole tablets', title_uk: 'Пантопразол/омепразрол таб.' },
      { id: '15', quantity: 0, title_en: 'Antacid tablets/gels', title_uk: 'Від печії таблетки/гелі' },
      { id: '16', quantity: 0, title_en: 'Sedative tablets and drops', title_uk: 'Заспокійливі таблетки та краплі' },
      { id: '17', quantity: 0, title_en: 'Ceftriaxone 1.0 ampoule', title_uk: 'Цефтріаксон 1.0 фл' },
      { id: '18', quantity: 0, title_en: 'Lidocaine 2%', title_uk: 'Лідокаїн 2%' },
      { id: '19', quantity: 0, title_en: 'Venotonics tablets/ointments', title_uk: 'Венотоніки таб/мазі' },
      { id: '20', quantity: 0, title_en: 'Tranexamic acid ampoules', title_uk: 'Транексамова кислота ампули!!!' },
      { id: '21', quantity: 0, title_en: 'Sorbents', title_uk: 'Сорбенти' },
      {
        id: '22',
        quantity: 0,
        title_en: 'Loperamide, Nifuroxazide, Levomycetin',
        title_uk: 'Лоперамід,Ніфуроксазид,Левоміцетин',
      },
      { id: '23', quantity: 0, title_en: 'Chlorhexidine', title_uk: 'Хлоргекседин ' },
      { id: '24', quantity: 0, title_en: 'Betadine, iodine, green stuff', title_uk: 'Бетадин,йод,зеленка' },
      {
        id: '25',
        quantity: 0,
        title_en: 'Mechanical blood pressure monitor, semi-automatic',
        title_uk: 'Тонометр механіка,напівавтоматичний',
      },
      { id: '26', quantity: 0, title_en: 'Regular thermometers', title_uk: 'Термометри звичайні' },
      {
        id: '27',
        quantity: 0,
        title_en: 'Wide elastic bandages, bandage rolls size 3, 4',
        title_uk: 'Еластичні бинти широкі, бинти-бандажі 3,4розмір',
      },
      {
        id: '28',
        quantity: 0,
        title_en: 'Fabric/silicone adhesive tape rolls',
        title_uk: 'Пластир котушки тканинний/силіклновий',
      },
      { id: '29', quantity: 0, title_en: 'Infusion systems', title_uk: 'Системи ПР' },
      {
        id: '30',
        quantity: 0,
        title_en: 'Syringes with needles 5.0, 10.0, 20.0',
        title_uk: 'Шприці з голками 5.0,10.0,20.0',
      },
      { id: '31', quantity: 0, title_en: 'IV catheters G 14, 16, 18, 20', title_uk: 'Катетори в/в G 14,16,18,20' },
      {
        id: '32',
        quantity: 0,
        title_en: 'М/L/XL Latex, nitrile gloves M/L/XL',
        title_uk: 'Рукавички н/ст латексні,нітрилові',
      },
      { id: '33', quantity: 0, title_en: 'Pulse oximeter', title_uk: 'Пульсоксиметр' },
    ],
  },
  {
    id: '3',
    title_uk: 'Їжа',
    title_en: 'Food',
    items: [
      { id: '1', quantity: 0, title_en: 'Canned meats', title_uk: 'Консерви м’ясні' },
      { id: '2', quantity: 0, title_en: 'Pâtés', title_uk: 'Паштети' },
      { id: '3', quantity: 0, title_en: 'Canned fish', title_uk: 'Консерви рибні' },
      { id: '4', quantity: 0, title_en: 'Canned vegetables', title_uk: 'Консерви овочеві' },
      { id: '5', quantity: 0, title_en: 'Canned fruits', title_uk: 'Консерви фруктові' },
      { id: '6', quantity: 0, title_en: 'Dried sausage', title_uk: 'Ковбаса вялена' },
      { id: '7', quantity: 0, title_en: 'Condensed milk', title_uk: 'Згущене молоко' },
      { id: '8', quantity: 0, title_en: 'Coffee', title_uk: 'Кава' },
      { id: '9', quantity: 0, title_en: 'Tea', title_uk: 'Чай' },
      { id: '10', quantity: 0, title_en: 'Oil', title_uk: 'Олія' },
      { id: '11', quantity: 0, title_en: 'Dehydrated food', title_uk: 'Сублімована їжа' },
      { id: '12', quantity: 0, title_en: 'MREs (Meal, Ready-to-Eat)', title_uk: 'Сухпайки' },
    ],
  },
];
